# ========== GUI SETTINGS ==========
gui:
  nerdFontsVersion: "3"
  sidePanelWidth: 0.2
  theme:
    activeBorderColor:
      - "#f5e0dc"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    selectedRangeBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#f5e0dc"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
      - bold
    markedBaseCommitFgColor:
      - "#89b4fa"
    markedBaseCommitBgColor:
      - "#f9e2af"
  filterMode: fuzzy
  showDivergenceFromBaseBranch: arrowAndNumber
# ========== GIT SETTINGS ==========
git:
  paging:
    externalDiffCommand: difft --color=always --syntax-highlight=on
  parseEmoji: true
# ========== OS SETTINGS ==========
os:
  editPreset: "nvim"
# ========== CUSTOM COMMANDS ==========
customCommands:
  # --- Create Conventional Commit ---
  - key: "<c-v>"
    context: "global"
    description: "Create Commit"
    prompts:
      - type: "menu"
        key: "Type"
        title: "Type of change"
        options:
          - name: "build"
            description: "Changes that affect the build system or external dependencies"
            value: "build"
          - name: "feat"
            description: "A new feature"
            value: "feat"
          - name: "fix"
            description: "A bug fix"
            value: "fix"
          - name: "chore"
            description: "Other changes that don't modify src or test files"
            value: "chore"
          - name: "ci"
            description: "Changes to CI configuration files and scripts"
            value: "ci"
          - name: "docs"
            description: "Documentation only changes"
            value: "docs"
          - name: "perf"
            description: "A code change that improves performance"
            value: "perf"
          - name: "refactor"
            description: "A code change that neither fixes a bug nor adds a feature"
            value: "refactor"
          - name: "revert"
            description: "Reverts a previous commit"
            value: "revert"
          - name: "style"
            description: "Changes that do not affect the meaning of the code"
            value: "style"
          - name: "test"
            description: "Adding missing tests or correcting existing tests"
            value: "test"
      - type: "input"
        title: "message"
        key: "Message"
        initialValue: ""
      - type: "confirm"
        key: "Confirm"
        title: "Commit"
        body: "Are you sure you want to commit?"
    command: "git commit --message '[{{.Form.Type}}]: {{.Form.Message}}'"
    loadingText: "Creating conventional commit..."
    output: log
  # --- Pull from Specific Remote ---
  - key: "p"
    description: "Pull from a specific remote repository"
    context: "global"
    loadingText: "Pulling ..."
    prompts:
      - type: "menuFromCommand"
        title: "Which remote repository to push to?"
        command: bash -c "git remote --verbose | grep '(push)'"
        filter: '(?P<remote>\S+)\s+(?P<url>\S+)\s+\(push\)'
        valueFormat: "{{ .remote }}"
        labelFormat: "{{ .remote | bold | cyan }} {{ .url }}"
    command: git pull {{index .PromptResponses 0}} {{ .CheckedOutBranch.Name }}
  # --- Push to a Specific Remote Repository ---
  - key: "P"
    description: "Push to a specific remote repository"
    context: "global"
    loadingText: "Pushing ..."
    prompts:
      - type: "menuFromCommand"
        title: "Which remote repository to push to?"
        command: bash -c "git remote --verbose | grep '(push)'"
        filter: '(?P<remote>\S+)\s+(?P<url>\S+)\s+\(push\)'
        valueFormat: "{{ .remote }}"
        labelFormat: "{{ .remote | bold | cyan }} {{ .url }}"
      - type: "menu"
        title: "How to push?"
        options:
          - value: "push"
          - value: "push --force-with-lease"
    command: "git {{index .PromptResponses 1}} {{index .PromptResponses 0}}"
