#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

[default_session]
preview_command = "eza -l --all --git --icons --color=always --no-user --no-permissions {}"

[[session]]
name = "Machine Status"
path = "~"
startup_command = "mole status"

[[session]]
name = "AI"
path = "~"
startup_command = "opencode"
windows = [ "codex", "gemini", "copilot", "shell"]

[[window]]
name = "codex"
path = "~"
startup_script = "codex"

[[window]]
name = "gemini"
path = "~"
startup_script = "gemini"

[[window]]
name = "copilot"
path = "~"
startup_script = "copilot"

[[window]]
name = "shell"
path = "~"

[[session]]
name = "Learn"
path = "~/Thoughts/Areas/productivity"
startup_command = "yazi"
windows = [ "FreeCodeCamp", "NeetCode", "OutSystems"]

[[window]]
name = "FreeCodeCamp"
path = "~/Thoughts/Projects/FreeCodeCamp"
startup_script = "yazi"

[[window]]
name = "NeetCode"
path = "~/Thoughts/Projects/Neetcode"
startup_script = "yazi"

[[window]]
name = "OutSystems"
path = "~/Thoughts/Projects/OutSystems"
startup_script = "yazi"
