import = ["~/.config/alacritty/catppuccin-mocha.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Fullscreen"

option_as_alt = "Both"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

size = 14

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On" }

[mouse]
hide_when_typing = true
